project:
  type: website
  title: "Year 9 Science"
  output-dir: docs

website:
  title: "Year 9 Science"
  navbar:
    left:
      - href: index.qmd

format:
  html:
    theme: flatly
    css: styles.css
    html-math-method: katex
